language: cpp
compiler:
  - clang
  - gcc
before_install:
  - sudo sh -c "echo 'deb http://llvm.org/apt/precise/ llvm-toolchain-precise main' >> /etc/apt/sources.list"
  - wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key | sudo apt-key add -
  - sudo add-apt-repository -y ppa:yjwong/gflags
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
install:
  - sudo apt-get install -qq llvm-3.4-dev libgflags-dev g++-4.8
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
script: cmake . && make -j
after_script: ./run_tests.sh
notifications:
  recipients:
    - dma+github@stripysock.com
  email:
    on_success: change
    on_failure: always
os:
  - linux
  - osx

